"""Decision 007 proof of concept (docs/plans/any_scenario_poc.md): deterministic checks over recorded evidence.

No model calls. The truck world under spikes/any-scenario-2026-10/evidence/truck was generated by the
layer-1 pipeline (ODD -> bundle -> mechanics -> checks -> rule-writer repairs); the run is the recorded
LLM-resident run with the station's fuel set to zero, in which the game master wrote rules mid-run.
"""
from __future__ import annotations

import gzip
import json
import re
import sys
from copy import deepcopy
from pathlib import Path

import unittest

REPO = Path(__file__).resolve().parents[1]
SPIKE = REPO / "spikes/any-scenario-2026-10"
TRUCK = SPIKE / "evidence/truck"
sys.path[:0] = [str(REPO), str(REPO / "src"), str(SPIKE)]

from checks import attempt_findings, conservation_findings, run_checks  # noqa: E402
from scripts.run_authored_world import build_engine  # noqa: E402
from world_substrate.mechanisms.time import ClockAdvanceProcess  # noqa: E402


def _load(name: str):
    return json.loads((TRUCK / name).read_text())


def _jsonl_gz(path: Path) -> list[dict]:
    with gzip.open(path, "rt") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def _vehicle(bundle: dict) -> dict:
    return next(e for e in bundle["entities"] if e["id"] == "delivery-vehicle")


def check_truck_world_passes_static_and_simulation_checks():
    report = run_checks(_load("bundle.json"), _load("causal.json"), stocks=_load("model.json")["stock_map"])
    assert report["counts"]["blocking"] == 0, [f["finding"] for f in report["findings"] if f["blocking"]]
    assert report["counts"]["rules_fired"] == report["counts"]["rules"]


def check_attempt_starts_without_fuel_and_world_stops_it_later():
    bundle = _load("bundle.json")
    _vehicle(bundle)["components"]["vehicle"]["fuel"] = 0
    engine, _, _ = build_engine(bundle, _load("causal.json"))
    engine.registry.register_process(ClockAdvanceProcess())
    offered = engine.discover("delivery-driver", kind="drive")["available"]
    assert offered, "driving must be offered on an empty tank: permissibility only, no feasibility gate"
    attempt = engine.submit(dict(offered[0]["action"], controller="test"))
    assert attempt["status"] == "accepted"
    vehicle = engine.world.entities["delivery-vehicle"].as_dict()["components"]["vehicle"]
    assert vehicle["operational_status"] == "attempting to drive"
    events = engine.advance(1)["events"]
    stop = [e for e in events if e["rule_id"] == "stop-delivery-vehicle-without-fuel"]
    assert len(stop) == 1
    after = engine.world.entities["delivery-vehicle"].as_dict()["components"]["vehicle"]
    assert after["operational_status"] == "stopped" and after["road_position"] == 0


def check_attempt_check_flags_a_fuel_gate_on_driving():
    causal = deepcopy(_load("causal.json"))
    assert attempt_findings(_load("bundle.json"), causal) == []
    drive = next(m for m in causal["mechanics"] if m["action_kind"] == "drive")
    drive["checks"].append({"label": "the vehicle has fuel", "op": "gt", "right": {"literal": 0},
                            "left": {"participant": {"name": "vehicle", "path": "components.vehicle.fuel"}}})
    findings = attempt_findings(_load("bundle.json"), causal)
    assert [f["rule"] for f in findings] == [drive["mechanic_id"]]


def check_conservation_flags_fuel_created_from_nothing():
    causal = deepcopy(_load("causal.json"))
    assert conservation_findings(causal) == []
    causal["processes"].append({
        "process_id": "free-fuel", "rationale": "test", "checks": [],
        "selector": {"categories": ["vehicle"], "components": ["vehicle"]},
        "effects": [{"op": "add", "participant": "it", "path": "components.vehicle.fuel", "value": {"literal": 1}}]})
    assert [f["rule"] for f in conservation_findings(causal)] == ["free-fuel"]


def check_removing_the_out_of_fuel_rule_is_caught():
    causal = deepcopy(_load("causal.json"))
    causal["processes"] = [p for p in causal["processes"] if p["process_id"] != "stop-delivery-vehicle-without-fuel"]
    report = run_checks(_load("bundle.json"), causal, stocks=_load("model.json")["stock_map"])
    assert report["counts"]["blocking"] > 0


def check_recorded_run_state_comes_only_from_engine_events():
    """Parallel-implementation check: replaying the run's Engine event changes over the initial state
    reproduces the final world exactly, so no other path (Concordia state, the runner) mutated it."""
    summary = json.loads((TRUCK / "run/summary.json").read_text())
    bundle = json.loads((TRUCK / "run/bundle_after_run.json").read_text())
    state = {e["id"]: deepcopy(e["components"]) for e in bundle["entities"]}
    for cond in summary["conditions_changed"]:
        eid, comp, field = cond["field"].split(".")
        state[eid][comp][field] = cond["to"]
    for ev in _jsonl_gz(TRUCK / "run/events.jsonl.gz"):
        assert ev["event_id"] and ev["cause"]
        for change in ev["changes"]:
            parts = change["path"].split(".")
            if len(parts) == 5 and parts[0] == "entities" and parts[2] == "components":
                assert state[parts[1]][parts[3]][parts[4]] == change["before"]
                state[parts[1]][parts[3]][parts[4]] = change["after"]
    final = json.loads((TRUCK / "run/final_world.json").read_text())["entities"]
    for eid, components in state.items():
        assert final[eid]["components"] == components


def check_resident_learned_out_of_fuel_by_observation():
    attempts = _jsonl_gz(TRUCK / "run/attempts.jsonl.gz")
    stop = next(e for e in _jsonl_gz(TRUCK / "run/events.jsonl.gz") if e["rule_id"] == "stop-delivery-vehicle-without-fuel")
    before = [a for a in attempts if a["tick"] == stop["tick"] - 1][0]
    after = [a for a in attempts if a["tick"] == stop["tick"]][0]
    assert before["performed"]["status"] == "accepted"  # it was allowed to try
    assert before["observed_effect"] == {"Delivery vehicle.operational_status": ["operational", "stopped"]}
    assert "Delivery vehicle.operational_status: stopped" in after["cited_observations"]


def check_game_master_wrote_one_rule_and_fell_back_to_one_ruling():
    summary = json.loads((TRUCK / "run/summary.json").read_text())
    written = summary["rules_written_mid_run"]
    ruled = [w for w in written if not w["written_mid_run"]]
    installed = [w for w in written if w["written_mid_run"]]
    assert ruled and any("from nothing" in f for f in ruled[0]["checks"]["findings_on_new_rule"])
    assert installed and installed[0]["status"] == "accepted"
    events = {e["event_id"]: e for e in _jsonl_gz(TRUCK / "run/events.jsonl.gz")}
    assert events[ruled[0]["event_id"]]["status"] == "unsupported_action"  # ruling: recorded, no state change
    assert events[installed[0]["event_id"]]["rule_id"] in installed[0]["rules_installed"]


def check_rule_written_mid_run_resolves():
    """The accepted mid-run rule must lead somewhere: an installed process fires and the run reaches its end."""
    summary = json.loads((TRUCK / "run/summary.json").read_text())
    installed = [w for w in summary["rules_written_mid_run"] if w["written_mid_run"]][0]["rules_installed"]
    fired = [e for e in _jsonl_gz(TRUCK / "run/events.jsonl.gz")
             if e["rule_id"] in installed and (e.get("causal_bearer") or {}).get("kind") == "process"]
    assert fired and fired[-1]["status"] == "accepted"
    assert summary["ended"] == "terminal"
    final = json.loads((TRUCK / "run/final_world.json").read_text())["entities"]["delivery-vehicle"]
    assert final["components"]["vehicle"]["road_position"] == 120


def check_single_duration_primitive():
    hits = []
    for root in ("src", "reference_worlds", "spikes"):
        for path in (REPO / root).rglob("*.py"):
            for line in path.read_text(errors="ignore").splitlines():
                if re.match(r"\s*class \w*(Activity|Attempt)State\b", line):
                    hits.append(str(path.relative_to(REPO)))
    assert hits == ["reference_worlds/waltzman/components.py"], hits


class AnyScenarioPocTests(unittest.TestCase):
    """Run by the project gate (scripts/check_project.py uses unittest discover)."""

    def test_truck_world_passes_static_and_simulation_checks(self):
        check_truck_world_passes_static_and_simulation_checks()

    def test_attempt_starts_without_fuel_and_world_stops_it_later(self):
        check_attempt_starts_without_fuel_and_world_stops_it_later()

    def test_attempt_check_flags_a_fuel_gate_on_driving(self):
        check_attempt_check_flags_a_fuel_gate_on_driving()

    def test_conservation_flags_fuel_created_from_nothing(self):
        check_conservation_flags_fuel_created_from_nothing()

    def test_removing_the_out_of_fuel_rule_is_caught(self):
        check_removing_the_out_of_fuel_rule_is_caught()

    def test_recorded_run_state_comes_only_from_engine_events(self):
        check_recorded_run_state_comes_only_from_engine_events()

    def test_resident_learned_out_of_fuel_by_observation(self):
        check_resident_learned_out_of_fuel_by_observation()

    def test_game_master_wrote_one_rule_and_fell_back_to_one_ruling(self):
        check_game_master_wrote_one_rule_and_fell_back_to_one_ruling()

    def test_rule_written_mid_run_resolves(self):
        check_rule_written_mid_run_resolves()

    def test_single_duration_primitive(self):
        check_single_duration_primitive()


if __name__ == "__main__":
    unittest.main(verbosity=2)
