(define (problem constrained_handoff-problem)
 (:domain constrained_handoff-domain)
 (:objects
   ana bo cy dev - member
   delivery_report_token delivery_report_link - delivery
   report_token report_link - information
   handoff_gate - gate
   handoff_token queue_capacity link_health safety_window - resource
   s_ops_chat s_radio - symbol
 )
 (:init
              (cat_member ana)
              (has_member ana)
              (cat_member bo)
              (has_member bo)
              (cat_member cy)
              (has_member cy)
              (cat_member dev)
              (has_member dev)
              (member_authorized dev)
              (cat_prereq_a handoff_token)
              (cat_restorable handoff_token)
              (has_resource handoff_token)
              (= (resource_current handoff_token) 0)
              (= (resource_required handoff_token) 1)
              (cat_prereq_b queue_capacity)
              (has_resource queue_capacity)
              (= (resource_current queue_capacity) 1)
              (= (resource_required queue_capacity) 1)
              (cat_prereq_c link_health)
              (has_resource link_health)
              (= (resource_current link_health) 1)
              (= (resource_required link_health) 1)
              (cat_prereq_d safety_window)
              (has_resource safety_window)
              (= (resource_current safety_window) 1)
              (= (resource_required safety_window) 1)
              (cat_gate handoff_gate)
              (has_gate handoff_gate)
              (gate_status handoff_gate s_blocked)
              (= (gate_approval_count handoff_gate) 0)
              (= (gate_required_approvals handoff_gate) 2)
              (cat_information report_token)
              (has_information report_token)
              (information_source_id report_token dev)
              (information_channel_id report_token s_ops_chat)
              (cat_delivery delivery_report_token)
              (has_delivery delivery_report_token)
              (delivery_info_id delivery_report_token report_token)
              (delivery_recipient_id delivery_report_token ana)
              (delivery_channel_id delivery_report_token s_ops_chat)
              (delivery_status delivery_report_token s_pending)
              (cat_information report_link)
              (has_information report_link)
              (information_source_id report_link dev)
              (information_channel_id report_link s_radio)
              (cat_delivery delivery_report_link)
              (has_delivery delivery_report_link)
              (delivery_info_id delivery_report_link report_link)
              (delivery_recipient_id delivery_report_link bo)
              (delivery_channel_id delivery_report_link s_radio)
              (delivery_status delivery_report_link s_pending)
              (same_delivery_channel_id__information_channel_id delivery_report_token report_token)
              (same_delivery_channel_id__information_channel_id delivery_report_link report_link)
              (= (gate_approval_count ana) 0)
              (= (gate_approval_count bo) 0)
              (= (gate_approval_count cy) 0)
              (= (gate_approval_count dev) 0)
              (= (gate_approval_count handoff_token) 0)
              (= (gate_approval_count queue_capacity) 0)
              (= (gate_approval_count link_health) 0)
              (= (gate_approval_count safety_window) 0)
              (= (gate_approval_count report_token) 0)
              (= (gate_approval_count delivery_report_token) 0)
              (= (gate_approval_count report_link) 0)
              (= (gate_approval_count delivery_report_link) 0)
              (= (gate_required_approvals ana) 0)
              (= (gate_required_approvals bo) 0)
              (= (gate_required_approvals cy) 0)
              (= (gate_required_approvals dev) 0)
              (= (gate_required_approvals handoff_token) 0)
              (= (gate_required_approvals queue_capacity) 0)
              (= (gate_required_approvals link_health) 0)
              (= (gate_required_approvals safety_window) 0)
              (= (gate_required_approvals report_token) 0)
              (= (gate_required_approvals delivery_report_token) 0)
              (= (gate_required_approvals report_link) 0)
              (= (gate_required_approvals delivery_report_link) 0)
              (= (resource_current ana) 0)
              (= (resource_current bo) 0)
              (= (resource_current cy) 0)
              (= (resource_current dev) 0)
              (= (resource_current handoff_gate) 0)
              (= (resource_current report_token) 0)
              (= (resource_current delivery_report_token) 0)
              (= (resource_current report_link) 0)
              (= (resource_current delivery_report_link) 0)
              (= (resource_required ana) 0)
              (= (resource_required bo) 0)
              (= (resource_required cy) 0)
              (= (resource_required dev) 0)
              (= (resource_required handoff_gate) 0)
              (= (resource_required report_token) 0)
              (= (resource_required delivery_report_token) 0)
              (= (resource_required report_link) 0)
              (= (resource_required delivery_report_link) 0)
 )
 (:goal (and 
           (gate_status handoff_gate s_ready)
        )
 )
)
